Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'  

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
