name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
            
jobs:
  ci-workflow:
    name: CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v2

      - name: Setup ruby
        id: setup-ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Install gems
        id: install-gems
        run: make bundle   

      - name: Run linter
        id: run-lint
        run: make lint

      - name: Run tests
        id: run-tests
        run: make  test 
